.travis.yml
Use of `system_site_packages: true` has been deprecated. This builds scipy in the virtualenv.
=> Fix broken Travis CI builds

MANIFEST.in
Tried to pip install the package but it failed due to a missing DESCRIPTION.txt file. Added a MANIFEST.in file with includes for DESCRIPTION.txt. Also added includes in the MANIFEST.in file for requirements.txt and LICENSE to conform to generally accepted practices for MANIFEST.in files.
=> Adds MANIFEST.in file

tests/test_bestfit.py, tests/test_yb_rcmod.py
The test failures are caused by not running in an interactive
environment. Using the "Agg" backend should solve this issue.
=> Fixed matplotlib test failures.

tests/test_style/test_colors.py, tests/test_style/test_palettes.py, yellowbrick/classifier/boundaries.py, yellowbrick/classifier/threshold.py, yellowbrick/features/pcoords.py, yellowbrick/features/radviz.py, yellowbrick/features/scatter.py, yellowbrick/style/colors.py, yellowbrick/style/palettes.py
This PR provides fixes to the `resolve_colors` function and adds a test suite to guard against regression. I've also reimplemented `resolve_colors` on the feature visualizers that had it commented out to use `get_color_cycle` instead. 
This PR unblocks #321 -- however, a more extensive overhaul of color and color handling in YB is required. We have 4 different methodologies that are mixed and matched in kind of a strange fashion. More than that, Yellowbrick-specific requirements have emerged. Briefly, they are:
- We need discrete colors that are visually separate for classes 
- We need continuous colors for regression values and heatmaps 
Both of these requirements are specified by the target variable. Finally, we need helpers for the other utilities we use; but those can be largely …
=> Fixes to the resolve colors function

README.md, docs/about.rst, docs/api/anscombe.rst, docs/api/datasets.rst, docs/api/index.rst, docs/api/palettes.rst, docs/changelog.rst, docs/evaluation.rst, docs/quickstart.rst
#328 issue
This pull request includes my initial edits and updates to the Yellowbrick documentation. The majority of the changes are stylistic and intended to create a uniform style that will help prevent any confusion for new and returning users. 
One of the edits you'll notice most often is that I changed all mentions of `Scikit-Learn` to `scikit-learn` unless it is at the beginning of a sentence. In that case, I've changed it to `Scikit-learn`. These changes will make our documentation consistent with scikit-learn's, which clarifies it's correct name and usage on their [faq](http://scikit-learn.org/stable/faq.html).
Other naming updates I made were to make sure that `Yellowbrick` was capitalized and `matplotlib` was not (unless at the beginning of a sentence, in a section header, or as …
=> Documentation updates

tests/test_classifier/test_class_prediction_error.py
In previous PR #355 , I switched to using sklearn "make_classification" function
to create test data.  However, I forgot to remove the hard-coded test data that
was being replaced. 👎 
This commit removes the numpy arrays that represent the test data
This commit also removes the numpy import statement
=> Remove hard-coded test data I left by accident

tests/test_cluster/test_elbow.py, yellowbrick/cluster/elbow.py
We identified an issue finding the centroid of a sparse matrix (`scipy.sparse.csc_matrix` and `scipy.sparse.csr_matrix`) -- the SciPy mean returns a 2D array instead of an array of 1 dimension less than the input (like NumPy does). I used a fairly naive check, `scipy.sparse.issparse` to check the matrix then updated the array correctly. Added tests for CSR, CSC, as well as DataFrames to `test_elbow.py`
Fixes #370
=> Updates the distortion score metric to handle sparse matrices

docs/about.rst, docs/contributing.rst
Updates our documentation to include contact info via GitHub, our Google Groups mailing list, Twitter, and StackOverflow. Also references MAINTAINERS.md and the contributors page on GitHub.
Fixes #260
=> Adds listserv to documentation

docs/api/contrib/index.rst, docs/api/contrib/statsmodels.rst, tests/test_contrib/test_statsmodels/__init__.py, tests/test_contrib/test_statsmodels/test_base.py, yellowbrick/contrib/statsmodels/__init__.py, yellowbrick/contrib/statsmodels/base.py
This PR places the lightweight wrapper suggested by @ianozsvald in `yellowbrick.contrib` to implement Yellowbrick visualizers with StatsModels. It also adds a documentation stub and test stubs, though it could certainly benefit from more from `statsmodels` users. 
Resolves #306: A new issue should be created to update and document this wrapper if required.
=> Adds StatsModelsWrapper to contrib.

.travis.yml
Looks like this failing job is suggesting running the following command before installing dependencies:
https://travis-ci.org/DistrictDataLabs/yellowbrick/jobs/378804441
`sudo apt-get update`
Let's open this PR to see if it fixes it.
@DistrictDataLabs/team-oz-maintainers
=> Add apt-get update command to the travis script

docs/api/classifier/classification_report.rst
The documentation was not updated to show that Classification Report now has a support parameter.  The example code was missing the support parameter, however the CR displayed a 'support' score.  I corrected the code by adding ```support=True```
=> Fix: If applied it corrects error in documentation for Classification Report Visualizer

docs/api/features/pca.rst
In the rst file of principal component analysis, which is located
in docs/api/features/pca.rst, "principal" was misspelled as "principle"
This was corrected because we want to keep our documentation in
tip-top shape.  Our documentation sets us apart from other projects
=> Fixes #433 - Correct spelling of "Principal" in PCA rst

DESCRIPTION.rst, README.md, docs/api/text/dispersion.rst, docs/index.rst
Added links to the dispersion plot from the main documentation home
page, the README, and DESCRIPTION.
=> Link Dispersion Plot from index and README

tests/test_features/test_manifold.py, yellowbrick/features/manifold.py
Some manifolds do not provide a `transform()` method since the data transformation process cannot be decoupled from the `fit()` process. In this case, the user is required to call `fit_transform()` to get the transformed data. Unfortunately, the `Manifold` visualizer implemented the `TransformerMixn` and `fit()` and `transform()` methods, so when calling the default `fit_transform()` method an exception was raised.
Because the `fit()` method already called `fit_transform()` - the fix was simple. `Manifold` now overrides `fit_transform()` to do the work that `fit()` used to do, and `fit()` simply calls `fit_transform()`. In addition, I've captured `AttributeError` exceptions in `transform()` and reraised them with a message that indicates the user should use `fit_transform()` instead. …
=> Fixes Manifold fit_transform bug.

CONTRIBUTING.md
Updates Yellowbrick's contributing guidelines by recommending that, ideally, a pull request should be able to be in completed in 6 weeks. While this is not a hard deadline, it should help new contributors scope their ideas.
=> Add recommended timeline to contributing guidelines

yellowbrick/regressor/residuals.py
Currently, the ResidualsPlot visualizer's histogram only displays the
frequency distribution when the ``hist`` argument is set to True.
This commit adds the option for probability density function(PDF).
This change allows for direct specification of density or frequency via
the ``hist`` argument.  By default, 'frequency' will be plotted.
``` python
from sklearn.linear_model import LinearRegression
from sklearn.datasets import make_regression
from sklearn.model_selection import train_test_split as tts
from yellowbrick.regressor import ResidualsPlot
X, y = make_regression(
n_samples=500, n_features=22, n_informative=8, random_state=42,
noise=0.2, bias=0.2,
)
X_train, X_test, y_train, y_test = tts(
X, y, test_size=0.2, random_state=11
)
visualizer = ResidualsPlot(LinearRegression(), …
```
=> Fixes #523, Adds probability density function to ResidualsPlot's histogram

yellowbrick/cluster/elbow.py
In the KElbowVisualizer's docstring, the possible values for the parameter `metric` were mistakenly named as `distortion_score`, `silhouette_score`, and `calinski_harabaz_score`. This commit updates them to the correct values: `distortion`, `silhouette`, and `calinksi_harabaz`
Fixes #529
=> [#529] Fix argument names in K-Elbow docstring

docs/api/text/corpus.rst
The link to the Baleen RSS Corpus was broken, so I replaced it with a link its [GitHub repository](https://github.com/DistrictDataLabs/baleen).
=> Fix link to Baleen RSS Corpus

docs/api/classifier/classification_report.rst, docs/api/classifier/rocauc.rst, docs/api/features/manifold.rst, docs/api/features/pcoords.rst, docs/api/features/radviz.rst, docs/api/features/rankd.rst, docs/api/model_selection/cross_validation.rst, docs/api/model_selection/learning_curve.rst, docs/api/model_selection/validation_curve.rst, docs/api/regressor/alphas.rst, docs/api/regressor/peplot.rst, docs/api/target/class_balance.rst, docs/api/text/dispersion.rst
I removed the deprecated `as_matrix` method from the code examples in Yellowbrick's documentation.
I also added comments or made small text changes to the comments in the code examples to help give our documentation a more uniform appearance. For example:
```
features = ["feature1", "feature2"]
target = "target variable"
X = data[features]
y = data[target]
```
And in the cases where I made small changes, I'll comments to files to help explain. Just let me know if you have any questions!
=> Update the text of documentation code examples

docs/api/features/rankd.rst
The `Rank2D` visualizer uses the Pearson score by default but the documentation says it uses `covariance` as the default ranking algorithm (and shows an example with the code and an image). Next, it is followed by an example using the Pearson score by setting `algorithm='pearson'`. 
So I not only updated the text but I also moved the example using the Pearson score above the covariance example since I think it makes more sense to first show the visualizer using the default settings and then show ways that it can be customized.
Resolves: #660
=> Update default ranking algorithm in Rank2D docs

docs/requirements.txt, requirements.txt, tests/requirements.txt
matplotlib 3.0.0 had introduced a bug which caused some issues with some of the visualizations. matplotlib 3.0.1 and above corrects the issue. This PR reinstates mpl 3.x support.
Specifically, it reverts the matplotlib version restriction introduced by: https://github.com/DistrictDataLabs/yellowbrick/pull/618
It replaces it with !=3.0.0. That way it'll skip the problematic version 3.0.0 but allow later 3.0.x versions.
Ran the tests using make test, no issues, but I don't know if there are extra tests to run.
=> Reinstate mpl 3

requirements.txt, setup.cfg, tests/conftest.py, tests/requirements.txt
The release of pytest 4.2 broke some of our custom pytest-spec related code (e.g. how the test report is printed). This PR attempts to solve some of the issues, but I've also [opened an issue](https://github.com/pchomik/pytest-spec/issues/21) with pytest-spec to see if we can resolve some of the warnings and add the parametrize ids back into the code base.
=> Fix errors related to release of pytest 4.2

README.md, docs/contributing/developing_visualizers.rst
Adds documentation for the `yellowbrick.download` script that is
included for dataset management. The documentation is located in both
the README.md and in the contributor's guide. This documentation will
hopefully also assist developers who are having trouble with older
dataset versions on their computers.
Closes #693
=> Documents the yellowbrick.download script.

docs/requirements.txt, requirements.txt, tests/requirements.txt, tests/test_classifier/test_confusion_matrix.py, tests/test_classifier/test_threshold.py, tests/test_contrib/test_scatter.py
This hotfix primarily adds matplotlib3 support by requiring any version of mpl except for 3.0.0 which had a backend bug that affected Yellowbrick.
@ianozsvald thanks for your note on #701 -- I'm not sure at this point what would be required to hotfix 0.9, we've made a lot of significant changes for our upcoming v1.0 release. However, I've created this PR to see what our CI tools think of the hotfix. Stay tuned!
=> Hotfix v0.9.1: matplotlib 3 support

docs/changelog.rst
This PR adds a small note to the changelog in the docs about the hotfix we pushed earlier this evening & the tag to the [release](https://github.com/DistrictDataLabs/yellowbrick/releases/tag/v0.9.1).
=> Adds hotfix tag and summary to changelog in docs

.appveyor.yml, .travis.yml, tests/requirements.txt
This PR is a workaround to the issue described in #744 by using the "Previous Visual Studio 2015" image rather than the current CI image. 
See [discussion here](https://help.appveyor.com/discussions/problems/20308-importerror-dll-load-failed-the-specified-module-could-not-be-found).
=> Workaround for AppVeyor Miniconda3 Tests

yellowbrick/datasets/base.py, yellowbrick/datasets/manifest.json
Numpy dataset loader requires allow_pickle=False to protect from
vulnerability. This required converting the game and mushroom datasets
into a Unicode dtype rather than the object dtype.
Fixes #765
=> Forces datasets loader to forbid pickle

docs/teaching.rst
Just realized that the original link to the "Teaching ML with YB" slidedeck in the docs was to speakerdeck and not to the specific slides (so the link worked, but each time new slides were uploaded, that new deck appeared first instead of the intended deck). This PR updates the link by pinning to the specific slide deck that teachers can use for teaching with YB in their courses.
=> Fixed incorrect link to teaching with YB slidedeck

docs/api/features/pcoords.rst
The normalization technique 'maxabs' is a supported method for ParallelCoordinates which is not referenced in the documentation.
=> Added normalization technique 'maxabs' reference to ParallelCoordinates documentation (DistrictDataLabs #797)

tests/test_regressor/test_residuals.py, yellowbrick/regressor/residuals.py
The following changes were made to Residuals referenced in #590:
1. Added new parameters train_alpha and test_alpha to specify the opacity of train and test data respectively in `residuals.py`
2. Modified the `test_residuals.py`
The result obtained is attached below:
=> Addressing issue #590:Adding train alpha and test alpha to residual

tests/requirements.txt
We've been experiencing a new set of CI test failures on Travis and Appveyor; it looks like the newest version of Matplotlib, which was released two days ago, [has made changes to how the backend is set](https://matplotlib.org/3.1.0/users/whats_new.html). 
As a result, when we run [`matplotlib.use("Agg")` for our tests](https://github.com/DistrictDataLabs/yellowbrick/blob/develop/tests/__init__.py#L24), it doesn't seem to work as expected anymore. This manifests in CI as a few image comparison failures (e.g. with `RFECV` and `ClassBalance`), but on my Mac it *also* results in about 75 of these: 
```
base.py:72: in setUp
self.assertEqual(self._backend, 'agg')
E   AssertionError: 'MacOSX' != 'agg'
E   - MacOSX
E   + agg
```
In this PR, I've updated our `tests/requirements.txt` to …
=> Temporarily sidestep matplotlib 3.1.0 in tests

CONTRIBUTING.md, docs/contributing/getting_started.rst, docs/quickstart.rst
This PR executes a few minor documentation changes:
- clarifies procedures for submitting PRs by giving a sense of what to expect from ideation to completion (closes #849)
- removes references to waffle (which is being deprecated) (closes #850)
- adds full name of NLTK (closes #841)
=> Doc updates to address waffle, PR procedure, and NLTK reference

docs/contributing/advanced_development_topics.rst, docs/index.rst
This update to the contributor's guide updates the "Releases" Advanced Topic to include information about how to build and deploy the release to PyPI and Anaconda. These notes are from my v0.9.1 build and deploy this evening.
=> Deploy Documentation

.github/PULL_REQUEST_TEMPLATE.md
@rebeccabilbro here are the revisions I mentioned yesterday. Basically, I've put the instructions in HTML comments so that the contributor can use the template to mostly fill in the blanks. There is still plenty of uncommented content, so it will be easy to tell if a contributor submits without using the template. Additionally, I've turned the checklist into a checkbox checklist so that the maintainers can also check things off as they're doing their review (it may not be a bad idea to put a maintainer checklist in the template as well).
=> PR Template Revisions

.appveyor.yml
Commenting out appveyor tests for MINICONDA_VERSION: "4.5.12"
Failing Tests Due to TypeError: LoadLibrary()
This seems to be a possible solution, but CI is building slowly:
https://github.com/mattwthompson/mbuild/commit/963ff7832f247cd77afaeec168988c99e3ccb6c0
=> comment out 4.5.12 miniconda build

docs/index.rst, docs/oneliners.rst
This PR is a step towards #600, adding a page in our documentation about using the quick methods.
1. Added a `oneliners.rst` to the `docs`; the page uses the plot directive to auto-generate the images when the docs are built.
2. Updated the `index.rst` to reference `oneliners.rst`
=> Add new oneliners page to the YB docs

docs/changelog.rst
This PR adds in the names of the Yellowbrick advisors to the v1.0 changelog to recognize their leadership contributions!
=> Adds advisors names to release changelog

docs/api/model_selection/learning_curve.rst
This is a minor typo correction. Corrects a line on the `learning_curve.rst` file. Specifics described below.
1. Edited 'two' to 'to' in second line of the opening summary of `'learning_curve.rst` since former made no sense.
=> Minor typo correction

docs/api/model_selection/cross_validation.rst, tests/test_model_selection/test_cross_validation.py, yellowbrick/model_selection/cross_validation.py
This PR addresses issue #960 
1. Added show hyperparameter to cv_scores.
2. Updated test for the quick method
3. Updated documentation
```python
from sklearn.linear_model import Ridge
from sklearn.model_selection import KFold
from yellowbrick.datasets import load_energy
from yellowbrick.model_selection import cv_scores
X, y = load_energy()
cv = KFold(n_splits=12, random_state=42)
model = Ridge()
visualizer = cv_scores(model, X=X, y=y, cv=cv, scoring='r2')
```
=> CVScores quick method update 

yellowbrick/cluster/elbow.py
This PR corrects the latex formatting in the legend of the `KElbowVisualizer` to close #1058, and also turns `frameon=True` for the legend to make it a bit easier to see over the gridlines and plot.
Formerly:
With this change:
=> Correct latex formatting in elbow legend

docs/api/features/manifold.rst
Fixing a typo in the documentation when importing manifold_embedding using the quick method
=> Fix a typo in the documentation updating manifold.rst

docs/api/contrib/index.rst, docs/api/contrib/scatter.rst, docs/api/contrib/statsmodels.rst, docs/api/contrib/wrapper.rst, tests/requirements.txt, tests/test_contrib/test_wrapper.py, yellowbrick/contrib/__init__.py, yellowbrick/contrib/wrapper.py, yellowbrick/exceptions.py, yellowbrick/utils/helpers.py, yellowbrick/utils/types.py
Adds a wrapper for estimators that implement the scikit-learn API but do not extend BaseEstimator. If the estimator is missing required properties (generally the learned attributes) then a sensible error is raised. Includes documentation about how to use non-sklearn estimators with Yellowbrick.
Fixes #1098
Fixes #1099
Fixes #397
Related to #1066
1. Added a `ContribEstimator` wrapper and helper functions to wrap cuML, catboost, neuraxle etc estimators
2. Wrapper allows access to estimator functions, raising sensible error if required attr is not available
2. Wrapper allows model type checking e.g. `is_classifier` 
2. Adapted our `is_estimator` and `get_model_name` helpers to use the `ContribEstimator` 
3. Removed recursive imports from …
=> Third Party Estimator Wrapper

docs/faq.rst
This small PR adds an additional FAQ to help direct inquiries to our wrapper documentation when they are using third-party estimators with Yellowbrick.
=> Ands a FAQ on our new wrapper

docs/api/text/dispersion.rst, tests/requirements.txt, tests/test_contrib/test_missing/test_bar.py, tests/test_contrib/test_missing/test_dispersion.py, tests/test_text/test_dispersion.py, yellowbrick/text/dispersion.py
This PR addresses a bug I recently noticed after reading a [stackoverflow post about changing the title of a dispersion plot](https://stackoverflow.com/questions/65384398/change-title-in-a-dispersion-plot-created-with-yellowbrick), which noted that it was not possible to change the title of the plot without explicitly calling `set_title`. Since `DispersionPlot` makes a call to `super` in `__init__`, this should be handled by the base class logic.
1. Updated the `DispersionPlot` to allow custom titles and colorization.
2. Fleshed out the docstrings and documentation a bit to provide explanations and examples of the optional parameters.
3. Updated some of the internal variable names to differentiate between similar sounding things (e.g. …
=> Update dispersion plot to allow title and color customization

docs/changelog.rst, yellowbrick/base.py
This PR fixes #1153, removing the print inside `set_params` impacting model visualizers
=> Fixes hanging print impacting model visualizers

yellowbrick/target/feature_correlation.py
When using ax param in the FeatureCorrelation visualizer to specify an axes location within a matplotlib subplot, it would not plot in the correct position.  However, it would create an entirely new plot
To fix this, I changed the ax in the Super init so it was not explicitly setting it to None which was preventing axes from being specified
Before:
After:
Fixes #1163
=> Fixes #1163 The  inability to place FeatureCorrelation Visualizations into subplots.

docs/requirements.txt, requirements.txt, tests/requirements.txt
This follows up on #1176 to also allow Numpy 1.20+ for end users of the library.
The end user problem is that Pip's new dependency resolver can get very ornery when an user attempts to install a new Numpy alongside Yellowbrick; if one is unlucky, it'll spend a long time trying to find a constellation of (various data science) packages that would accept Numpy < 1.20 to satisfy the pin in Yellowbrick's requirements.
This places the onus of properly locking dependency versions (with e.g. `pip-tools` or `poetry`) on the end user, as it should be.
1. Removed the `<1.20` numpy pin from the `requirements.txt` files that had been untouched by #1176.
I've elided editing the changelog here, since it looks like there have been several other changes since 1.3.post1 …
=> Allow Numpy 1.20+

tests/test_cluster/test_elbow.py, yellowbrick/cluster/elbow.py
This PR fixes  #1185 which ValueError is thrown when not all cluster center has at least one input data point assigned to it.
1. Instead of reassigning [`labels = le.fit_transform(labels)`](https://github.com/DistrictDataLabs/yellowbrick/blob/783069e082569463faa3a192d1884de627a13370/yellowbrick/cluster/elbow.py#L90), modification were made to just call `le.fit(labels)` without reassigning input argument `labels`.
```
import numpy as np
from yellowbrick.cluster import distortion_score
X = np.array([[1,2],[3,4],[5,6]])
labels = np.array([1,3,3])
print(distortion_score(X, labels))
labels = np.array([0,1,1])
print(distortion_score(X, labels))
```
Console Output
```
4.000000000000001
4.000000000000001
```
Still to do:
None
Questions for the …
=> Fix KElbowVisualizer ValueError when null cluster is encountered

CONTRIBUTING.md, tests/test_classifier/test_threshold.py, yellowbrick/classifier/threshold.py
Although documentation allows `DiscriminationThreshold(model, argmax=None)`, current implementation raises an exception since it assumes `argmax` to be a string.
1. Allow `argmax` to be `None` (as already documented)
2. Raise error in case `argmax` is an invalid metric (similar to the check of `exclude`)
3. Add tests to check `argmax`
4. Improve docs of `argmax` and `exclude`
5. Fix typo in `CONTRIBUTING.md`
=> Better argmax handling in DiscriminationThreshold

yellowbrick/regressor/prediction_error.py, yellowbrick/regressor/residuals.py
This PR fixes #1209 so that the is_fitted parameter is no longer being overwritten by the default setting.
1. I updated the super for both ResidualsPlot and PredictionError to include is_fitted as a parameter
2. I deleted the self assignment of `is_fitted` in both visualizers
=> Fixed #1209 `is_fitted` parameter not setting to given value

tests/test_regressor/test_prediction_error.py, tests/test_regressor/test_residuals.py
This PR adds tests to #1221. These tests assure us that the is_fitted param's state is maintained when the visualizer is instantiated.
1. Added test for ResidualPlots
2. Added test for PredictionError
3. Removed unnecessary import so that flake8 passed
=> Create tests for `is_fitted` parameter for ResidualsPlot and PredictionError

.github/workflows/ci.yml, .pre-commit-config.yaml, CONTRIBUTING.md, README.md, docs/contributing/getting_started.rst, requirements.txt, setup.cfg
This PR fixes #456 which requested a pre-commit hook for `black`.
1. Added `.pre-commit-config.yaml` to configure pre-commit hooks.
Since we are deciding how best to have people set up the hook, here is an example of how to do so with the YAML file included in the first commit:
```shell
pip install pre-commit
pre-commit install      # run this from the yellowbrick folder after checking out this branch
```
To start with, I have provided the following hooks:
- removal of trailing whitespace
- fix end of file
- check that the YAML for the config is valid
- check that the commit won't be adding large files
- run `black`
The pre-commit hooks run automatically once you run `git commit`. Note that you don't have to install `black` because the first time you run …
=> Implement black code formatting as pre-commit hook

.github/workflows/ci.yml, .github/workflows/linting.yml
Continuation of https://github.com/DistrictDataLabs/yellowbrick/pull/1269 to only run the linting job for pull requests.
1. Removed the linting job from the main CI workflow.
2. Created a new linting workflow with just the linting job to run only for pull requests.
=> Only run linting actions on PRs.
