DistrictDataLabs/yellowbrick

linebestfit.py

Returns plot with line of best fit and scatter plot of data.

Linear Regression function. 

---

yellowbrick/classifier/rocauc.py

@bbengfort  Added x and y axis to ROC curve. Updated example in docstring.

ROCAUC needs X/Y axis labels 

---

tests/test_style/test_palettes.py
yellowbrick/style/palettes.py

An additional color palette to memorialize some of the more interesting colors developed by a neural network in this blog post: http://lewisandquark.tumblr.com/
Original issue: https://github.com/DistrictDataLabs/yellowbrick/issues/235

235 Neural Paint color palette

---

yellowbrick/features/jointplot.py

Cleanup of #243. No change in functionality.

Refactor of test of matplotlib version. Suggested by @bbengfort.

---

yellowbrick/features/pca.py

I was looking over the documentation I provided in the PCA visualize and thought it was in rough shape. A few typos.

updating docstrings in pca.py file

---

docs/contributing.rst

Simply adding some documentation on how to write image comparison tests.

Update docs/contributing.rst with Image Comparison Test section 

---

tests/test_base.py
yellowbrick/base.py

Hi this is what I've done so far.
Apologies, this is my first contribution and I'm trying to get the hang of Git

#161 Created @property for visualizer size.

---

yellowbrick/text/__init__.py
yellowbrick/text/dispersion.py

Builds DispersionPlotVisualizer that shows the occurence of a word in a
corpus and the distance each word is from the beginning of the corpus.
Still to do!
Below is an example.
```from nltk.corpus import gutenberg
words = ['Elinor', 'Marianne', 'Edward', 'Willoughby']
text = gutenberg.words('austen-sense.txt')
viz = DispersionPlotVisualizer(words, color='b')
viz.fit(text)
viz.poof()
```

Fix #147 Implements a lexical dispersion plot

---

tests/test_contrib/test_scatter.py

This PR implements a mock test to ensure `alpha` is passed to the `ax.scatter` as well as cleans up a couple of other tests that I spotted while I was there. 
@peterespinosa I wanted to provide this for reference in case it helps with writing other tests without having to deal with image similarity! I've added some pointers as comments in the code.

Minor updates to contrib ScatterViz tests

---

examples/jlinGG/Interactive_YB_classifiers.ipynb

This pull request adds a jupyter notebook example illustrating the use of ipywidgets to create an interactive model selection demo.

Adding interactive classifier example

---

yellowbrick/cluster/silhouette.py

This PR adds parameters, attributes, and an example to the SilhouetteVisualizer docstring, fixing #583.

Finishes SilhouetteVisualizer docstring, completing #583

---

tests/test_text/test_freqdist.py
yellowbrick/regressor/residuals.py

Closes #616 by adding color parameter with color selection to accompanying residual horizontal histogram.

Adding color selection to ResidualsPlot() histogram

---

examples/examples.ipynb

I found that 'confusion matrix' example in the example.ipynb does not have an explanation. what is it and how useful to the data science project.

adding explanation for the confusion matrix example

---

examples/agodbehere/PytorchExample.html
examples/agodbehere/PytorchExample.ipynb

Note that pytorch must be installed. This isn't a simple dependency, as installation process currently depends on hardware and OS.

Added example demonstrating how to use yellowbrick with pytorch models.

---

README.md
docs/about.rst

Updates our documentation with the JOSS paper citation and links.

JOSS paper citation

---

docs/governance.rst
docs/index.rst

This PR moves the governance document from the Google Docs draft to our public documentation. I would appreciate a review to make sure it is readable after the copy and paste. I would also like to consider the merge of this PR the formal ratification of this document by Yellowbrick.

Governance Document

---

docs/contributing/getting_started.rst

replaced with valid conda envs url

---

docs/governance.rst
docs/index.rst

I have made the following changes 👍 
made index page more helpful to potential users and users with issues
_If you've added to the docs_
- _Have you built the docs using `make html`?_
Yes

makes documentation index page more concise

---

docs/governance.rst

Last night during the board of advisors meeting we voted to accept an amendment to the governance document that adds a new role of mentor-contributor.

Governance Amendment: Mentor-Contributor

---

tests/test_regressor/test_alphas.py
tests/test_regressor/test_influence.py
tests/test_regressor/test_residuals.py
yellowbrick/regressor/alphas.py
yellowbrick/regressor/base.py
yellowbrick/regressor/influence.py
yellowbrick/regressor/residuals.py

This PR is towards #669 and #456 and #600 and #509 but focused on the `yellowbrick.regressor` module.
1. General linting and applied black formatting to the files & code header updates.
2. Updated quick methods to return the visualizer
3. Added in some TODOs to guide follow-on PRs
4. Enhanced `ResidualsScoreVisualizer` to store `score_`.

Regressors Audit

---

tests/test_cluster/test_base.py
tests/test_cluster/test_elbow.py
tests/test_cluster/test_icdm.py
tests/test_cluster/test_silhouette.py
yellowbrick/cluster/base.py
yellowbrick/cluster/elbow.py
yellowbrick/cluster/icdm.py
yellowbrick/cluster/silhouette.py

This PR is towards #669 and #456 and #600 and #509 but focused on the `yellowbrick.cluster` module.
1. General linting and applied black formatting to the files & code header updates.
2. Added in some TODOs to guide follow-on PRs
3. Enhanced `ClusterScoreVisualizer` and base tests with `force_model` argument in case user wants to bypass the sklearn estimator-appropriateness checks.

Clusterers Audit

---

tests/test_model_selection/conftest.py
tests/test_model_selection/test_cross_validation.py
tests/test_model_selection/test_learning_curve.py
tests/test_model_selection/test_validation_curve.py
tests/test_target/test_binning.py
tests/test_target/test_class_balance.py
tests/test_target/test_feature_correlation.py
yellowbrick/model_selection/cross_validation.py
yellowbrick/model_selection/learning_curve.py
yellowbrick/model_selection/validation_curve.py
yellowbrick/target/base.py
yellowbrick/target/binning.py
yellowbrick/target/class_balance.py
yellowbrick/target/feature_correlation.py

This PR is towards #669 and #456 and #600 and #509  but focused on the `yellowbrick.target` and `yellowbrick.model_selection` modules.
1. General linting and applied `black` formatting to the files & code header updates.
2. Updated quickmethods to return the visualizer 
3. Added in some TODOs to guide follow-on PRs

Target and Model Selection audit

---

docs/governance/index.rst
docs/governance/minutes/2019-09-09.rst

This PR adds the minutes from the Board of Advisors meeting held on September 9, 2019.

September 9, 2019 Minutes

---

CONTRIBUTING.md
DESCRIPTION.md
MAINTAINERS.md
README.md

This Pull Request updates a number of hyperlinks found in the repository's documentation (.md) files.
General edits include:
- correction of invalid hyperlinks; 
- addition of hyperlinks to unlinked text; 
- updated hyperlinks to point to more specific/relevant sections in the documentation; and
- Text was also modified to address typos (i.e., "gallary") or for consistency (i.e., "quickstart" vs "Quick Start").
I have made changes to the following files:
1.  CONTRIBUTING.md
2.  DESCRIPTION.md
3.  MAINTAINERS.md
4.  README.md

Update hyperlinks in repo documentation (.md) files.

---

docs/changelog.rst

This PR adds to the documentation a changelog for the v1.1 release.

Adds v1.1 changelog ahead of release

---

docs/api/regressor/influence.rst

This pull request addresses #885. I have added a couple lines of exposition and two plot directives to further illustrate the usage of the Cook's Distance visualizer.

Flesh out Cook's Distance documentation

---

docs/changelog.rst

Updates changelog with development efforts since v1.1 release.

Updates changelog with development efforts since v1.1 release.

---

docs/governance/index.rst
docs/governance/minutes/2020-05-13.rst
docs/governance/minutes/2020-10-06.rst

Creation of minutes for Advisory Meeetings
This PR fixes #issue_number _(If you are fixing a bug)_ which reported a bug that caused a problem to occur when users...
_(or if you are introducing a new feature)_ which requested a feature to allow the user to...
1.
2.
3.
_If you are adding or modifying a visualizer, PLEASE include a sample plot here along with the code you used to generate it._
Still to do:
Questions for the @DistrictDataLabs/team-oz-maintainers:

Create minutes for Advisory Meeting

---

README.md

This PR fixes a small bug in the README which neglected to fit the visualizer before scoring it.

small correction to model visualization section

---

docs/contributing/developing_visualizers.rst
tests/test_text/test_dispersion.py

1. Removed broken URL 
2. replaced it with a working one

Fix broken url to pytest fixtures

---

Makefile
setup.py

This PR fixes #1132. No changes to the `make test` flow for CI.
1. Remove pytest-runner from setup.py
2. Updates related config 
3. 
_If you are adding or modifying a visualizer, PLEASE include a sample plot here along with the code you used to generate it._
Still to do:
Questions for the @DistrictDataLabs/team-oz-maintainers:

#1132 - remove deprecated pytest-runner from testing

---

.gitattributes
.github/RELEASE_TEMPLATE.md
.github/workflows/ci.yml
docs/api/model_selection/cross_validation.rst
docs/conf.py
docs/contributing/developing_visualizers.rst
setup.py
tests/base.py
tests/test_classifier/test_prcurve.py
tests/test_cluster/test_elbow.py
tests/test_features/test_radviz.py
tests/test_features/test_rankd.py
tests/test_regressor/test_residuals.py
tests/test_style/test_rcmod.py
yellowbrick/contrib/missing/bar.py
yellowbrick/features/rankd.py

This PR fixes #1113 by handling some housekeeping issues. We've changed our master branch to the main branch and created a release issue template (though I don't think it is used automatically by GitHub). We've also checked the new pip resolver and all of our dependencies are compatible. This PR also updates our CI to test Python 3.8 and 3.9 to ensure we're testing on the latest version of Python.
This PR also addresses some warnings that were generated by the tests and fixes #707 
This PR also adds a .gitattributes to fix #1127
Other housekeeping items:
- Apparently Sphinx `add_stylesheet` [is deprecated](https://github.com/sphinx-doc/sphinx/issues/7747) so updated to use `add_css_file` instead. 
- The cross-validation doc images were not building, so fixed the code by adding …

Housekeeping

---

docs/governance/index.rst
docs/governance/minutes/2021-01-13.rst

Adding January 2021 Yellowbrick Board meeting minutes

January 2021 Meeting Minutes

---

tests/requirements.txt
yellowbrick/datasets/manifest.json

This PR performs a couple of minor maintenance items:
1. Switches to a YB-specific data lake for datasets storage
2. Updates nltk dependency that has a CVE
Other minor updates may follow; this PR will require a new release.

2022 Maintenance

---

docs/api/features/rankd.rst

This is my first PR to Yellowbrick.
I've made this change through the GitHub UI, is that OK? Or do I need to actually checkout the repo and install everything and build the docs?

Fixes minor typo in rank docs

---

yellowbrick/utils/kneed.py

Updated info of parameter y
This PR fixes #1236 (updates the description of parameter y)
1. Updated description of y as per mentioned in #1236

Update description of parameter y

---

docs/contributing/getting_started.rst

1. Fix typo in PR section of getting started docs (`essenence`&rarr; `essence`).

DOC Fix typo in PR section of getting started docs.
